version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-lr2
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "DERCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
